site_name: MkLorum
nav:
  - Home: index.md
  - About : about.md
  - User Guide:
        - Configuration: user-guid/configuration.md
        - Getting Start: user-guid/getting-started.md


theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
      - yaml
      - django

extra_css:
  - css/extra_css.css

